version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/conf:/etc/nginx/conf.d
      - ./volumes/vhost:/etc/nginx/vhost.d
      - ./volumes/html:/usr/share/nginx/html
      - ./volumes/dhparam:/etc/nginx/dhparam
      - ./volumes/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: nginx-proxy-le
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/conf:/etc/nginx/conf.d
      - ./volumes/vhost:/etc/nginx/vhost.d
      - ./volumes/html:/usr/share/nginx/html
      - ./volumes/dhparam:/etc/nginx/dhparam
      - ./volumes/certs:/etc/nginx/certs:rw
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=[your email here]

  # this service can be a separate file, remember to
  # leave networks declaration in both of those
  ddb-proxy:
    image: ghcr.io/mrprimate/ddb-proxy:latest
    environment:
      - VIRTUAL_HOST=ddb-proxy.example.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=ddb-proxy.example.com
networks:
  default:
    external:
      name: nginx-proxy
